//@ui5-bundle sap/ushell/components/workPageRuntime/Component-preload.js
sap.ui.require.preload({
	"sap/ushell/components/workPageRuntime/Component.js":function(){
//Copyright (c) 2009-2023 SAP SE, All Rights Reserved
sap.ui.define(["sap/ui/core/UIComponent"],function(t){"use strict";return t.extend("sap.ushell.components.workPageRuntime.Component",{metadata:{manifest:"json",library:"sap.ushell"},getNavigationDisabled:function(){var t=this.getComponentData()||{};return!!t.navigationDisabled},hideRuntime:function(){this.getRootControl().getController().hideRuntime()},onRouteMatched:function(){this.getRootControl().getController().onRouteMatched()}})});
},
	"sap/ushell/components/workPageRuntime/controller/WorkPageRuntime.controller.js":function(){
//Copyright (c) 2009-2023 SAP SE, All Rights Reserved
sap.ui.define(["sap/base/Log","sap/ui/core/mvc/Controller","sap/ushell/components/workPageRuntime/services/WorkPage","sap/base/util/deepExtend","sap/ushell/EventHub","sap/ushell/components/pages/controller/PagesAndSpaceId","sap/ushell/Config"],function(e,t,o,n,i,a,r){"use strict";return t.extend("sap.ushell.components.workPageRuntime.controller.WorkPageRuntime",{onInit:function(){var e=sap.ushell.Container.getRenderer();var t=new URLSearchParams(window.location.search);this.oWorkPageService=new o;this.oWorkPageNavContainer=this.byId("workpageNavContainer");this.oEmptyPage=this.byId("emptyPage");this._oWorkPageBuilderComponentCreatedPromise=new Promise(function(e,t){this._oWorkPageBuilderComponentResolve=e;this._oWorkPageBuilderComponentReject=t}.bind(this));return this._getPageId().then(function(o){this._sPageId=o;this._sSiteId=t.get("siteId")||r.last("/core/site/siteId");return this._onWorkPageLoad().finally(function(){i.emit("CenterViewPointContentRendered");if(!this.getOwnerComponent().getNavigationDisabled()){this.oContainerRouter=e.getRouter();this.oContainerRouter.getRoute("home").attachMatched(this.onRouteMatched.bind(this,false));this.oContainerRouter.getRoute("openFLPPage").attachMatched(this.onRouteMatched.bind(this,false))}}.bind(this))}.bind(this)).catch(this._handleErrors.bind(this))},_navigate:function(){this.oWorkPageNavContainer.to(this.byId("workPage"))},onWorkPageBuilderCreated:function(e){this._oWorkPageBuilderComponent=e.getParameter("component");this._oWorkPageBuilderComponentResolve(this._oWorkPageBuilderComponent)},_handleErrors:function(t){e.error("An error occurred while loading the page",t);e.debug("cep/editMode: on Route matched: Handle errors","Work Page runtime");this.oWorkPageNavContainer.to(this.byId("errorPage"))},onRouteMatched:function(){e.debug("cep/editMode: on Route matched","Work Page runtime");return this._getPageId().then(function(e){this._sPageId=e;return this._onWorkPageLoad()}.bind(this)).catch(this._handleErrors.bind(this))},_onWorkPageLoad:function(){this._oLoadWorkPageAndVisualizationsPromise=this.oWorkPageService.loadWorkPageAndVisualizations(this._sSiteId,this._sPageId);return Promise.all([this._oWorkPageBuilderComponentCreatedPromise,this._oLoadWorkPageAndVisualizationsPromise]).then(function(e){var t=e[0];var o=e[1];this._oOriginalData=n({},o);t.setPageData(o);this._navigate()}.bind(this))},_getPageId:function(){if(r.last("/core/workPages/myHome/pageId")){return Promise.resolve(r.last("/core/workPages/myHome/pageId"))}return a._getPageAndSpaceId().then(function(e){return e.pageId})},hideRuntime:function(){e.debug("cep/editMode: navigate to empty page","Page runtime");this.oWorkPageNavContainer.to(this.oEmptyPage)}})});
},
	"sap/ushell/components/workPageRuntime/manifest.json":'{"_version":"1.39.0","sap.app":{"id":"sap.ushell.components.workPageRuntime","applicationVersion":{"version":"1.115.1"},"ach":"CA-FLP-FE-UI","type":"component","title":""},"sap.ui":{"fullWidth":false,"technology":"UI5","deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"componentUsages":{"pageBuilder":{"name":"sap.ushell.components.workPageBuilder","lazy":true}},"componentName":"sap.ushell.components.workPageRuntime","rootView":{"viewName":"sap.ushell.components.workPageRuntime.view.WorkPageRuntime","type":"XML","async":true},"dependencies":{"minUI5Version":"1.99","libs":{"sap.ui.core":{},"sap.m":{}}},"contentDensities":{"compact":true,"cozy":true}}}',
	"sap/ushell/components/workPageRuntime/services/NavigationResolver.js":function(){
// Copyright (c) 2009-2023 SAP SE, All Rights Reserved
sap.ui.define(["sap/base/util/ObjectPath","sap/ui/core/Core","sap/ushell/Config","sap/base/Log"],function(e,t,n,o){"use strict";var r=function(){this._sBaseUrl=n.last("/core/workPages/navigationApiUrl");this._sSiteId=e.get("ushell.site.siteId",window["sap-ushell-config"])};r.prototype._fetchCsrfToken=function(){if(this._oFetchCsrfTokenPromise){return this._oFetchCsrfTokenPromise}this._oFetchCsrfTokenPromise=fetch(this._sBaseUrl,{method:"HEAD",headers:{"x-csrf-token":"fetch","Accept-Language":t.getConfiguration().getLanguageTag()}}).then(function(e){return e.headers.get("x-csrf-token")});return this._oFetchCsrfTokenPromise};r.prototype.resolveByInbound=function(e,n){return this._fetchCsrfToken().then(function(o){return fetch(this._sBaseUrl+"/resolve/inbound",{method:"POST",headers:{"Content-Type":"application/json; utf-8",Accept:"application/json","x-csrf-token":o,"Accept-Language":t.getConfiguration().getLanguageTag()},body:JSON.stringify({inboundIdentifier:e,intentParameters:n,queryParameters:{siteId:this._sSiteId},launchType:"standalone"})}).then(function(e){if(e.ok===false){return Promise.reject(e.statusText)}return e.json()}).then(function(e){var t=e.value||e;var n=Array.isArray(t)?t[0].url:t.url;return{additionalInformation:"",url:n,applicationType:"URL",navigationMode:"newWindow"}})}.bind(this)).catch(function(t){o.error("Tile target for inboundId '"+e+"' could not be resolved. The tile will be shown but will not navigate.");o.error(t);return{additionalInformation:"",url:"",applicationType:"URL",navigationMode:"newWindow"}})};return r},true);
},
	"sap/ushell/components/workPageRuntime/services/WorkPage.js":function(){
// Copyright (c) 2009-2023 SAP SE, All Rights Reserved
sap.ui.define(["sap/ui/core/Core","sap/ushell/utils/HttpClient","sap/base/util/ObjectPath","sap/ushell/Config","sap/base/Log"],function(e,t,a,r,s){"use strict";var i=function(){this.httpClient=new t;this._sBaseUrl=r.last("/core/workPages/contentApiUrl")};i.prototype._validateData=function(e){s.debug("cep/editMode: load Page: validate","Work Page service");if(e.errors&&e.errors.length>0){return Promise.reject(e.errors.map(function(e){return e.message}).join(",\n"))}if(!a.get("data.WorkPage",e)){s.debug("cep/editMode: load Page: validate: reject: data is empty","Work Page service");return Promise.reject("Work Page data is empty")}return Promise.resolve(e)};i.prototype.loadWorkPageAndVisualizations=function(e,t){var r="{"+"WorkPage("+'SiteId:"'+e+'",'+'WorkPageId:"'+t+'"'+") {"+"Id,"+"Contents,"+"Editable,"+"UsedVisualizations{"+"nodes{"+"Id,"+"Type,"+"Descriptor,"+"DescriptorResources{"+"BaseUrl,"+"DescriptorPath"+"}"+"}"+"}"+"}"+"}";return this._doRequest(r).then(this._validateData).then(function(e){var t=a.get("data.WorkPage.Contents",e);var r=a.get("data.WorkPage.UsedVisualizations.nodes",e)||[];var s=a.get("data.WorkPage.Editable",e)===true;return{WorkPage:{Contents:t,UsedVisualizations:{nodes:r},Editable:s}}})};i.prototype._doRequest=function(t){return this.httpClient.get(this._sBaseUrl+"?query="+t,{headers:{"Content-Type":"application/json",Accept:"application/json","Accept-Language":e.getConfiguration().getLanguageTag()}}).then(function(e){if(e.status<200||e.status>=300){return Promise.reject("HTTP request failed with status: "+e.status+" - "+e.statusText)}return JSON.parse(e.responseText||"{}")})};return i},true);
},
	"sap/ushell/components/workPageRuntime/view/WorkPageRuntime.view.xml":'<mvc:View\n    xmlns="sap.m"\n    xmlns:core="sap.ui.core"\n    xmlns:mvc="sap.ui.core.mvc"\n    controllerName="sap.ushell.components.workPageRuntime.controller.WorkPageRuntime"\n    height="100%"><NavContainer id="workpageNavContainer"><Page\n            id="workPage"\n            busy="{= !${/loaded}}"\n            enableScrolling="false"\n            showHeader="false"><core:ComponentContainer\n                height="100%"\n                usage="pageBuilder"\n                manifest="true"\n                async="true"\n                componentCreated="onWorkPageBuilderCreated"\n            /></Page><MessagePage\n            id="errorPage"\n            showHeader="false"\n            description="" /><Page\n            id="emptyPage"\n            showHeader="false" /></NavContainer></mvc:View>\n'
});
//# sourceMappingURL=Component-preload.js.map
